### ISSUE TITLE
Dockerfile should somehow handle certificates

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/adam#27]
The command: 
`docker run lfedge/adam server`
doesn't work correctly as the docker image does not have certificates. It also doesn't take them from the local build generated by `adam generate server` if I use `make image-local`

`error loading server cert run/adam/server.pem and server key run/adam/server-key.pem: open  run/adam/server.pem: no such file or directory`

**Comment by rvs** [comment]
Hey @mydatascience -- can you describe your ideal workflow with Docker?

**Comment by deitch** [comment]
I think you are right @mydatascience , but this is largely a documentation issue. When you run it in a container as `docker run`, it doesn't have any of the persistent data, specifically the adam runtime database, which by default is in `run/adam/`. So you need to run it `docker run -v $(pwd)/run:/run` or similar. I will update the docs.

**Comment by deitch** [comment]
@mydatascience is the documentation that exists not sufficient? See the readme [here](verifier creates it based on what it finds in /persist/download/*/verified), about halfway down that section where it talks about ephemeral directories?

**Comment by mydatascience** [comment]
I would suggest to set documentation in the way that a user that reads the main commands can just execute them.   
It is explained in the documentation, but without looking carefully and understanding the Adam database purpose (and meeting the error) I can't understand why should I use this command.
Ideally I would have a Dockerfile with some embedded certificates and an option to substitute them. Also there is a `make image` target that leads me to nowhere - I can't then use this Docker container

I will suggest an update to my PR24. Or we may think of updating the Dockerfile

**Comment by deitch** [comment]
> Dockerfile with some embedded certificates

We definitely should not embed certificates into the image.

I would consider having an option to `adam server` where it can auto-generate the certificates if they do not exist, and then and `adam admin` to get the public certificate. I like that endpoint anyways, so will add that immediately.

> Also there is a make image target that leads me to nowhere - I can't then use this Docker container since I can't follow the step adam generate server and I don't have ./run and ./bin

I think what you are saying is, the documentation about how to generate the certificates _when running in a docker container_ needs to be clearer. I will open an immediate PR on that, and then we can look at the other parts of changing the build order in the README.

**Comment by mydatascience** [comment]
Agreed. Let's have it this way and make it a default option.

**Comment by mydatascience** [comment]
> I would consider having an option to adam server where it can auto-generate the certificates if they do not exist, and then and adam admin to get the public certificate. I like that endpoint anyways, so will add that immediately. 

Agreed. Let's have it this way and make it a default option.

**Comment by deitch** [comment]
This is going to be very limited, since you need to pass it the CN and, more importantly, the SANs. It has no way of knowing how you will access it.

**Comment by mydatascience** [comment]
Maybe
 1) require parameters as cn and hostname for starting docker container.  
 2) get cn as hostname and hostname for local run as a default parameters. Anyway the certificates generated by adam generate are self-signed. 
Another option is to support Let's encrypt for the public installations.

**Comment by deitch** [comment]
> require parameters as cn and hostname for starting docker container

Well, it isn't the container as much as the binary.

I am going to start it without, where `--self-cert` just passes it `localhost, localhost.localdomain,127.0.0.1`. We can open another PR to make it better.

**Comment by rvs** [comment]
Also @mydatascience -- you should probably take a look at how embedded Adam takes care of all this in https://github.com/lf-edge/adam/blob/master/scripts/eve-embedded.sh
