### ISSUE TITLE
Link to "API-compliant Controller" isn't clickable

### ISSUE THREAD

**Issue by mperov** [lf-edge/adam#47]
## Description
There is link to API-compliant Controller in README.md, but I can't access to [API-compliant Controller](https://github.com/lf-edge/eve/blob/master/api/API.md)
I get **404 Error - Page not found**!

**Comment by mperov** [comment]
Link to **the official API** isn't working too.

**Comment by rvs** [comment]
Seems like typos. They should be pointing to https://github.com/lf-edge/eve/blob/master/api/README.md

Do you want to submit a Pull Request @mperov ?

**Comment by mperov** [comment]
@rvs yes, I do, so I submitted pull request from my fork of adam, please, consider it.

**Comment by deitch** [comment]
Closed via #49
