### ISSUE TITLE
newlog storing binary format rather than json

### ISSUE THREAD

**Issue by deitch** [lf-edge/adam#53]
The drivers all are supposed to store _json_ format, but the newlog endpoint is storing the _wire_ format.

For the newlog marshaling, which should be changed, see [here](https://github.com/deitch/adam/blob/b6d8baa3495b0f9d6352a627602cc565d572613d/pkg/server/apiHandler.go#L398) where it calls [proto.Marshal](https://godoc.org/google.golang.org/protobuf/proto#Marshal).

For the other marshaling, e.g. logs, see [here](https://github.com/deitch/adam/blob/b6d8baa3495b0f9d6352a627602cc565d572613d/pkg/server/apiHandler.go#L346) where it calls [protojson.Marshal](https://godoc.org/google.golang.org/protobuf/encoding/protojson#Marshal)

**Comment by deitch** [comment]
cc @giggsoff

**Comment by giggsoff** [comment]
But at the same time we use proto for info and metrics, so, we also need to change them?

**Comment by deitch** [comment]
Urgh. So we do. We need to make a conscious decision about it. Well, this issue is good for that.

My preference would be to store everything in universal format, as above. But make arguments the other way, if you have them?

**Comment by deitch** [comment]
Fixed by #55
